{% set name = "opentelemetry-instrumentation-falcon" %}
{% set version = "0.48b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_falcon-{{ version }}.tar.gz
  sha256: 9f0d6d72852e4a131c38499f2333d386a9362f9021d4b65646763026d64e7575

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation-wsgi ==0.48b0
    - opentelemetry-instrumentation ==0.48b0
    - opentelemetry-semantic-conventions ==0.48b0
    - opentelemetry-util-http ==0.48b0
    - packaging >=20.0
    # - parameterized ==0.7.4
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-falcon 
    # - falcon <4.0.0,>=1.4.1
    # - parameterized ==0.7.4
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-falcon 
    # - falcon <4.0.0,>=1.4.1
    # - parameterized ==0.7.4
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-falcon 
    # - falcon <4.0.0,>=1.4.1
    # - parameterized ==0.7.4
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-falcon 
    # - falcon <4.0.0,>=1.4.1
    # - parameterized ==0.7.4
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-instrumentation-falcon 
    # - falcon <4.0.0,>=1.4.1
    # - parameterized ==0.7.4
    # - opentelemetry-test-utils ==0.43b0
    # - opentelemetry-instrumentation-falcon 
    # - falcon <3.1.2,>=1.4.1
    # - opentelemetry-test-utils ==0.44b0
    # - opentelemetry-instrumentation-falcon 
    # - falcon <3.1.2,>=1.4.1
    # - falcon <3.1.2,>=1.4.1
    # - falcon <3.1.2,>=1.4.1
    # - falcon <3.1.2,>=1.4.1
    # - falcon <3.1.2,>=1.4.1

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-falcon
  summary: Falcon instrumentation for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
